version: '3.7'
services:
  client:
    restart: always
    image: harentius/attraction-wars-client
    ports:
      - 15670:80

  server:
    restart: always
    image: harentius/attraction-wars-server
    ports:
      - 15671:80
    environment:
      WORLD_WIDTH: 15000
      WORLD_HEIGHT: 15000
      ASTEROIDS_DENSITY: 1.25
