#!/bin/bash

docker pull harentius/attraction-wars-client
docker pull harentius/attraction-wars-server
docker pull harentius/attraction-wars-bots

docker-compose down -v --rmi local
docker-compose up -d
